// Copyright 2024 Indent Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: multiparty/prompt/v1/notify.proto

package promptv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateWebPushSubscriptionRequest is a request to create a web push-based prompt subscription.
type CreateWebPushSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SpaceName is the name of the space in which the prompt is being created.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	// Endpoint is the URL to which the push message will be sent.
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// ExpirationTime is the time at which the subscription will expire.
	ExpirationTime uint64 `protobuf:"varint,3,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	// Keys are the public keys used to encrypt the push message.
	Keys *WebPushSubscriptionKeys `protobuf:"bytes,4,opt,name=keys,proto3" json:"keys,omitempty"`
}

func (x *CreateWebPushSubscriptionRequest) Reset() {
	*x = CreateWebPushSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebPushSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebPushSubscriptionRequest) ProtoMessage() {}

func (x *CreateWebPushSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebPushSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateWebPushSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_notify_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWebPushSubscriptionRequest) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

func (x *CreateWebPushSubscriptionRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CreateWebPushSubscriptionRequest) GetExpirationTime() uint64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

func (x *CreateWebPushSubscriptionRequest) GetKeys() *WebPushSubscriptionKeys {
	if x != nil {
		return x.Keys
	}
	return nil
}

// WebPushSubscription is a subscription to a web push-based prompt.
type WebPushSubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Meta is the metadata for the subscription.
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Endpoint is the URL to which the push message will be sent.
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Keys are the public keys used to encrypt the push message.
	Keys *WebPushSubscriptionKeys `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"`
}

func (x *WebPushSubscription) Reset() {
	*x = WebPushSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebPushSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPushSubscription) ProtoMessage() {}

func (x *WebPushSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPushSubscription.ProtoReflect.Descriptor instead.
func (*WebPushSubscription) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *WebPushSubscription) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *WebPushSubscription) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WebPushSubscription) GetKeys() *WebPushSubscriptionKeys {
	if x != nil {
		return x.Keys
	}
	return nil
}

// WebPushSubscriptionKeys are the public keys used to encrypt the push message.
type WebPushSubscriptionKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// P256dh is the public key used to encrypt the push message.
	P256Dh string `protobuf:"bytes,1,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	// Auth is the authentication secret used to encrypt the push message.
	Auth string `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *WebPushSubscriptionKeys) Reset() {
	*x = WebPushSubscriptionKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebPushSubscriptionKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPushSubscriptionKeys) ProtoMessage() {}

func (x *WebPushSubscriptionKeys) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPushSubscriptionKeys.ProtoReflect.Descriptor instead.
func (*WebPushSubscriptionKeys) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_notify_proto_rawDescGZIP(), []int{2}
}

func (x *WebPushSubscriptionKeys) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *WebPushSubscriptionKeys) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

// GetSubscribeOptionsRequest is a request to get the options for subscribing.
type GetSubscribeOptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SpaceName is the name being subscribed to.
	SpaceName string `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
}

func (x *GetSubscribeOptionsRequest) Reset() {
	*x = GetSubscribeOptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscribeOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeOptionsRequest) ProtoMessage() {}

func (x *GetSubscribeOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribeOptionsRequest) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_notify_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscribeOptionsRequest) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

// SubscribeOptions are options for subscribing.
type SubscribeOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ApplicationServerKey is the ECDSA P-256 public key that the push server will use to authenticate your server.
	ApplicationServerKey string `protobuf:"bytes,1,opt,name=application_server_key,json=applicationServerKey,proto3" json:"application_server_key,omitempty"`
}

func (x *SubscribeOptions) Reset() {
	*x = SubscribeOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOptions) ProtoMessage() {}

func (x *SubscribeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOptions.ProtoReflect.Descriptor instead.
func (*SubscribeOptions) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_notify_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeOptions) GetApplicationServerKey() string {
	if x != nil {
		return x.ApplicationServerKey
	}
	return ""
}

var File_multiparty_prompt_v1_notify_proto protoreflect.FileDescriptor

var file_multiparty_prompt_v1_notify_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x21, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a,
	0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x75, 0x73, 0x68, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x50, 0x75,
	0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x73, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x13, 0x57, 0x65, 0x62,
	0x50, 0x75, 0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2e, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x65, 0x62, 0x50, 0x75, 0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22,
	0x45, 0x0a, 0x17, 0x57, 0x65, 0x62, 0x50, 0x75, 0x73, 0x68, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x32,
	0x35, 0x36, 0x64, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x32, 0x35, 0x36,
	0x64, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x3b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x16, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x42, 0xdf, 0x01,
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x44, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x4d, 0x50, 0x58, 0xaa, 0x02, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x14, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5c, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x20, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79,
	0x5c, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x3a, 0x3a, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiparty_prompt_v1_notify_proto_rawDescOnce sync.Once
	file_multiparty_prompt_v1_notify_proto_rawDescData = file_multiparty_prompt_v1_notify_proto_rawDesc
)

func file_multiparty_prompt_v1_notify_proto_rawDescGZIP() []byte {
	file_multiparty_prompt_v1_notify_proto_rawDescOnce.Do(func() {
		file_multiparty_prompt_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiparty_prompt_v1_notify_proto_rawDescData)
	})
	return file_multiparty_prompt_v1_notify_proto_rawDescData
}

var file_multiparty_prompt_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_multiparty_prompt_v1_notify_proto_goTypes = []interface{}{
	(*CreateWebPushSubscriptionRequest)(nil), // 0: multiparty.prompt.v1.CreateWebPushSubscriptionRequest
	(*WebPushSubscription)(nil),              // 1: multiparty.prompt.v1.WebPushSubscription
	(*WebPushSubscriptionKeys)(nil),          // 2: multiparty.prompt.v1.WebPushSubscriptionKeys
	(*GetSubscribeOptionsRequest)(nil),       // 3: multiparty.prompt.v1.GetSubscribeOptionsRequest
	(*SubscribeOptions)(nil),                 // 4: multiparty.prompt.v1.SubscribeOptions
	(*Meta)(nil),                             // 5: multiparty.prompt.v1.Meta
}
var file_multiparty_prompt_v1_notify_proto_depIdxs = []int32{
	2, // 0: multiparty.prompt.v1.CreateWebPushSubscriptionRequest.keys:type_name -> multiparty.prompt.v1.WebPushSubscriptionKeys
	5, // 1: multiparty.prompt.v1.WebPushSubscription.meta:type_name -> multiparty.prompt.v1.Meta
	2, // 2: multiparty.prompt.v1.WebPushSubscription.keys:type_name -> multiparty.prompt.v1.WebPushSubscriptionKeys
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_multiparty_prompt_v1_notify_proto_init() }
func file_multiparty_prompt_v1_notify_proto_init() {
	if File_multiparty_prompt_v1_notify_proto != nil {
		return
	}
	file_multiparty_prompt_v1_prompt_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_multiparty_prompt_v1_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebPushSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebPushSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebPushSubscriptionKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscribeOptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiparty_prompt_v1_notify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multiparty_prompt_v1_notify_proto_goTypes,
		DependencyIndexes: file_multiparty_prompt_v1_notify_proto_depIdxs,
		MessageInfos:      file_multiparty_prompt_v1_notify_proto_msgTypes,
	}.Build()
	File_multiparty_prompt_v1_notify_proto = out.File
	file_multiparty_prompt_v1_notify_proto_rawDesc = nil
	file_multiparty_prompt_v1_notify_proto_goTypes = nil
	file_multiparty_prompt_v1_notify_proto_depIdxs = nil
}
