// Copyright 2024 Indent Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: multiparty/prompt/v1/prompt.proto

package promptv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Prompt_Status int32

const (
	Prompt_UNKNOWN Prompt_Status = 0
	Prompt_OPEN    Prompt_Status = 1
	Prompt_CLOSED  Prompt_Status = 2
	Prompt_ERROR   Prompt_Status = 3
)

// Enum value maps for Prompt_Status.
var (
	Prompt_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "OPEN",
		2: "CLOSED",
		3: "ERROR",
	}
	Prompt_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"OPEN":    1,
		"CLOSED":  2,
		"ERROR":   3,
	}
)

func (x Prompt_Status) Enum() *Prompt_Status {
	p := new(Prompt_Status)
	*p = x
	return p
}

func (x Prompt_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Prompt_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_multiparty_prompt_v1_prompt_proto_enumTypes[0].Descriptor()
}

func (Prompt_Status) Type() protoreflect.EnumType {
	return &file_multiparty_prompt_v1_prompt_proto_enumTypes[0]
}

func (x Prompt_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Prompt_Status.Descriptor instead.
func (Prompt_Status) EnumDescriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{0, 0}
}

type Prompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// multiparty.v1.Meta meta = 1;
	Title string          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Form  *structpb.Value `protobuf:"bytes,3,opt,name=form,proto3" json:"form,omitempty"`
	// multiparty.jsonschema202012.JSONSchema schema = 4;
	Status Prompt_Status `protobuf:"varint,5,opt,name=status,proto3,enum=multiparty.prompt.v1.Prompt_Status" json:"status,omitempty"`
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *Prompt) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Prompt) GetForm() *structpb.Value {
	if x != nil {
		return x.Form
	}
	return nil
}

func (x *Prompt) GetStatus() Prompt_Status {
	if x != nil {
		return x.Status
	}
	return Prompt_UNKNOWN
}

type ListPromptsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space string `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
}

func (x *ListPromptsRequest) Reset() {
	*x = ListPromptsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPromptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsRequest) ProtoMessage() {}

func (x *ListPromptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsRequest.ProtoReflect.Descriptor instead.
func (*ListPromptsRequest) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *ListPromptsRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

type ListPromptsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompts []*Prompt `protobuf:"bytes,1,rep,name=prompts,proto3" json:"prompts,omitempty"`
}

func (x *ListPromptsResponse) Reset() {
	*x = ListPromptsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPromptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromptsResponse) ProtoMessage() {}

func (x *ListPromptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromptsResponse.ProtoReflect.Descriptor instead.
func (*ListPromptsResponse) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{2}
}

func (x *ListPromptsResponse) GetPrompts() []*Prompt {
	if x != nil {
		return x.Prompts
	}
	return nil
}

type GetPromptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space string `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPromptRequest) Reset() {
	*x = GetPromptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptRequest) ProtoMessage() {}

func (x *GetPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptRequest.ProtoReflect.Descriptor instead.
func (*GetPromptRequest) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{3}
}

func (x *GetPromptRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *GetPromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// multiparty.v1.Meta meta = 1;
	Prompt *Prompt `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// content matches prompt schema
	Content *structpb.Value `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetPrompt() *Prompt {
	if x != nil {
		return x.Prompt
	}
	return nil
}

func (x *Response) GetContent() *structpb.Value {
	if x != nil {
		return x.Content
	}
	return nil
}

type ListResponsesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space      string `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	PromptName string `protobuf:"bytes,2,opt,name=prompt_name,json=promptName,proto3" json:"prompt_name,omitempty"`
}

func (x *ListResponsesRequest) Reset() {
	*x = ListResponsesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponsesRequest) ProtoMessage() {}

func (x *ListResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponsesRequest.ProtoReflect.Descriptor instead.
func (*ListResponsesRequest) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponsesRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *ListResponsesRequest) GetPromptName() string {
	if x != nil {
		return x.PromptName
	}
	return ""
}

type ListResponsesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *ListResponsesResponse) Reset() {
	*x = ListResponsesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponsesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponsesResponse) ProtoMessage() {}

func (x *ListResponsesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponsesResponse.ProtoReflect.Descriptor instead.
func (*ListResponsesResponse) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponsesResponse) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetResponseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space string `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetResponseRequest) Reset() {
	*x = GetResponseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseRequest) ProtoMessage() {}

func (x *GetResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiparty_prompt_v1_prompt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseRequest.ProtoReflect.Descriptor instead.
func (*GetResponseRequest) Descriptor() ([]byte, []int) {
	return file_multiparty_prompt_v1_prompt_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponseRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *GetResponseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_multiparty_prompt_v1_prompt_proto protoreflect.FileDescriptor

var file_multiparty_prompt_v1_prompt_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x22, 0x2a, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x4d, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x72, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x06, 0x70, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0xdf, 0x01, 0x0a,
	0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x50, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x44, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x2e, 0x61, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x4d, 0x50, 0x58, 0xaa, 0x02, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x14, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5c, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5c,
	0x56, 0x31, 0xe2, 0x02, 0x20, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5c,
	0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x3a, 0x3a, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiparty_prompt_v1_prompt_proto_rawDescOnce sync.Once
	file_multiparty_prompt_v1_prompt_proto_rawDescData = file_multiparty_prompt_v1_prompt_proto_rawDesc
)

func file_multiparty_prompt_v1_prompt_proto_rawDescGZIP() []byte {
	file_multiparty_prompt_v1_prompt_proto_rawDescOnce.Do(func() {
		file_multiparty_prompt_v1_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiparty_prompt_v1_prompt_proto_rawDescData)
	})
	return file_multiparty_prompt_v1_prompt_proto_rawDescData
}

var file_multiparty_prompt_v1_prompt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_multiparty_prompt_v1_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_multiparty_prompt_v1_prompt_proto_goTypes = []interface{}{
	(Prompt_Status)(0),            // 0: multiparty.prompt.v1.Prompt.Status
	(*Prompt)(nil),                // 1: multiparty.prompt.v1.Prompt
	(*ListPromptsRequest)(nil),    // 2: multiparty.prompt.v1.ListPromptsRequest
	(*ListPromptsResponse)(nil),   // 3: multiparty.prompt.v1.ListPromptsResponse
	(*GetPromptRequest)(nil),      // 4: multiparty.prompt.v1.GetPromptRequest
	(*Response)(nil),              // 5: multiparty.prompt.v1.Response
	(*ListResponsesRequest)(nil),  // 6: multiparty.prompt.v1.ListResponsesRequest
	(*ListResponsesResponse)(nil), // 7: multiparty.prompt.v1.ListResponsesResponse
	(*GetResponseRequest)(nil),    // 8: multiparty.prompt.v1.GetResponseRequest
	(*structpb.Value)(nil),        // 9: google.protobuf.Value
}
var file_multiparty_prompt_v1_prompt_proto_depIdxs = []int32{
	9, // 0: multiparty.prompt.v1.Prompt.form:type_name -> google.protobuf.Value
	0, // 1: multiparty.prompt.v1.Prompt.status:type_name -> multiparty.prompt.v1.Prompt.Status
	1, // 2: multiparty.prompt.v1.ListPromptsResponse.prompts:type_name -> multiparty.prompt.v1.Prompt
	1, // 3: multiparty.prompt.v1.Response.prompt:type_name -> multiparty.prompt.v1.Prompt
	9, // 4: multiparty.prompt.v1.Response.content:type_name -> google.protobuf.Value
	5, // 5: multiparty.prompt.v1.ListResponsesResponse.responses:type_name -> multiparty.prompt.v1.Response
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_multiparty_prompt_v1_prompt_proto_init() }
func file_multiparty_prompt_v1_prompt_proto_init() {
	if File_multiparty_prompt_v1_prompt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiparty_prompt_v1_prompt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_prompt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPromptsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_prompt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPromptsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_prompt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_prompt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_prompt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponsesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_prompt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponsesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiparty_prompt_v1_prompt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiparty_prompt_v1_prompt_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multiparty_prompt_v1_prompt_proto_goTypes,
		DependencyIndexes: file_multiparty_prompt_v1_prompt_proto_depIdxs,
		EnumInfos:         file_multiparty_prompt_v1_prompt_proto_enumTypes,
		MessageInfos:      file_multiparty_prompt_v1_prompt_proto_msgTypes,
	}.Build()
	File_multiparty_prompt_v1_prompt_proto = out.File
	file_multiparty_prompt_v1_prompt_proto_rawDesc = nil
	file_multiparty_prompt_v1_prompt_proto_goTypes = nil
	file_multiparty_prompt_v1_prompt_proto_depIdxs = nil
}
