name: protobuf
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  protogen:
    name: protogen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run protogen
        run: make proto
      - name: Check Go codegen
        run: |
          ./scripts/check-change.sh \
              api/multiparty/v1/*.pb.go
      - name: Check Python codegen
        run: |
          ./scripts/check-change.sh \
              clients/python/api/multiparty/v1/*.py
