name: Pylint

on: [push]

defaults:
  run:
    working-directory: ./clients/python

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analyzing code with pylint
      run: |
        pylint $(git ls-files '*.py' | grep -v '_pb2.py')
    - name: Statically check code with mypy
      run: |
        mypy ./multiparty
