"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Indent Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class WebPushSubscription(google.protobuf.message.Message):
    """WebPushSubscription is a subscription to a web push-based prompt."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENDPOINT_FIELD_NUMBER: builtins.int
    EXPIRATION_TIME_FIELD_NUMBER: builtins.int
    KEYS_FIELD_NUMBER: builtins.int
    endpoint: builtins.str
    """Endpoint is the URL to which the push message will be sent."""
    expiration_time: builtins.int
    """ExpirationTime is the time at which the subscription will expire."""
    @property
    def keys(self) -> global___WebPushSubscriptionKeys:
        """Keys are the public keys used to encrypt the push message."""
    def __init__(
        self,
        *,
        endpoint: builtins.str = ...,
        expiration_time: builtins.int = ...,
        keys: global___WebPushSubscriptionKeys | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["keys", b"keys"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["endpoint", b"endpoint", "expiration_time", b"expiration_time", "keys", b"keys"]) -> None: ...

global___WebPushSubscription = WebPushSubscription

@typing_extensions.final
class WebPushSubscriptionKeys(google.protobuf.message.Message):
    """WebPushSubscriptionKeys are the public keys used to encrypt the push message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P256DH_FIELD_NUMBER: builtins.int
    AUTH_FIELD_NUMBER: builtins.int
    p256dh: builtins.str
    """P256dh is the public key used to encrypt the push message."""
    auth: builtins.str
    """Auth is the authentication secret used to encrypt the push message."""
    def __init__(
        self,
        *,
        p256dh: builtins.str = ...,
        auth: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["auth", b"auth", "p256dh", b"p256dh"]) -> None: ...

global___WebPushSubscriptionKeys = WebPushSubscriptionKeys
