"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Indent Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Prompt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Prompt._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Prompt._Status.ValueType  # 0
        OPEN: Prompt._Status.ValueType  # 1
        CLOSED: Prompt._Status.ValueType  # 2
        ERROR: Prompt._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    UNKNOWN: Prompt.Status.ValueType  # 0
    OPEN: Prompt.Status.ValueType  # 1
    CLOSED: Prompt.Status.ValueType  # 2
    ERROR: Prompt.Status.ValueType  # 3

    TITLE_FIELD_NUMBER: builtins.int
    FORM_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    title: builtins.str
    """multiparty.v1.Meta meta = 1;"""
    @property
    def form(self) -> google.protobuf.struct_pb2.Value: ...
    status: global___Prompt.Status.ValueType
    """multiparty.jsonschema202012.JSONSchema schema = 4;"""
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        form: google.protobuf.struct_pb2.Value | None = ...,
        status: global___Prompt.Status.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["form", b"form"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["form", b"form", "status", b"status", "title", b"title"]) -> None: ...

global___Prompt = Prompt

@typing_extensions.final
class ListPromptsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPACE_FIELD_NUMBER: builtins.int
    space: builtins.str
    def __init__(
        self,
        *,
        space: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["space", b"space"]) -> None: ...

global___ListPromptsRequest = ListPromptsRequest

@typing_extensions.final
class ListPromptsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPTS_FIELD_NUMBER: builtins.int
    @property
    def prompts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Prompt]: ...
    def __init__(
        self,
        *,
        prompts: collections.abc.Iterable[global___Prompt] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["prompts", b"prompts"]) -> None: ...

global___ListPromptsResponse = ListPromptsResponse

@typing_extensions.final
class GetPromptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPACE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    space: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        space: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "space", b"space"]) -> None: ...

global___GetPromptRequest = GetPromptRequest

@typing_extensions.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    @property
    def prompt(self) -> global___Prompt:
        """	multiparty.v1.Meta meta = 1;"""
    @property
    def content(self) -> google.protobuf.struct_pb2.Value:
        """content matches prompt schema"""
    def __init__(
        self,
        *,
        prompt: global___Prompt | None = ...,
        content: google.protobuf.struct_pb2.Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["content", b"content", "prompt", b"prompt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["content", b"content", "prompt", b"prompt"]) -> None: ...

global___Response = Response

@typing_extensions.final
class ListResponsesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPACE_FIELD_NUMBER: builtins.int
    PROMPT_NAME_FIELD_NUMBER: builtins.int
    space: builtins.str
    prompt_name: builtins.str
    def __init__(
        self,
        *,
        space: builtins.str = ...,
        prompt_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["prompt_name", b"prompt_name", "space", b"space"]) -> None: ...

global___ListResponsesRequest = ListResponsesRequest

@typing_extensions.final
class ListResponsesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSES_FIELD_NUMBER: builtins.int
    @property
    def responses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Response]: ...
    def __init__(
        self,
        *,
        responses: collections.abc.Iterable[global___Response] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["responses", b"responses"]) -> None: ...

global___ListResponsesResponse = ListResponsesResponse

@typing_extensions.final
class GetResponseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPACE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    space: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        space: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "space", b"space"]) -> None: ...

global___GetResponseRequest = GetResponseRequest
