# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiparty/prompt/v1/prompt.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!multiparty/prompt/v1/prompt.proto\x12\x14multiparty.prompt.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xbf\x01\n\x06Prompt\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12*\n\x04\x66orm\x18\x03 \x01(\x0b\x32\x16.google.protobuf.ValueR\x04\x66orm\x12;\n\x06status\x18\x05 \x01(\x0e\x32#.multiparty.prompt.v1.Prompt.StatusR\x06status\"6\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\n\n\x06\x43LOSED\x10\x02\x12\t\n\x05\x45RROR\x10\x03\"*\n\x12ListPromptsRequest\x12\x14\n\x05space\x18\x01 \x01(\tR\x05space\"M\n\x13ListPromptsResponse\x12\x36\n\x07prompts\x18\x01 \x03(\x0b\x32\x1c.multiparty.prompt.v1.PromptR\x07prompts\"<\n\x10GetPromptRequest\x12\x14\n\x05space\x18\x01 \x01(\tR\x05space\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"r\n\x08Response\x12\x34\n\x06prompt\x18\x02 \x01(\x0b\x32\x1c.multiparty.prompt.v1.PromptR\x06prompt\x12\x30\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x16.google.protobuf.ValueR\x07\x63ontent\"M\n\x14ListResponsesRequest\x12\x14\n\x05space\x18\x01 \x01(\tR\x05space\x12\x1f\n\x0bprompt_name\x18\x02 \x01(\tR\npromptName\"U\n\x15ListResponsesResponse\x12<\n\tresponses\x18\x01 \x03(\x0b\x32\x1e.multiparty.prompt.v1.ResponseR\tresponses\">\n\x12GetResponseRequest\x12\x14\n\x05space\x18\x01 \x01(\tR\x05space\x12\x12\n\x04name\x18\x02 \x01(\tR\x04nameB\xdf\x01\n\x18\x63om.multiparty.prompt.v1B\x0bPromptProtoP\x01ZDmultiparty.ai/api/multiparty/prompt/v1/multiparty/prompt/v1;promptv1\xa2\x02\x03MPX\xaa\x02\x14Multiparty.Prompt.V1\xca\x02\x14Multiparty\\Prompt\\V1\xe2\x02 Multiparty\\Prompt\\V1\\GPBMetadata\xea\x02\x16Multiparty::Prompt::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiparty.prompt.v1.prompt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.multiparty.prompt.v1B\013PromptProtoP\001ZDmultiparty.ai/api/multiparty/prompt/v1/multiparty/prompt/v1;promptv1\242\002\003MPX\252\002\024Multiparty.Prompt.V1\312\002\024Multiparty\\Prompt\\V1\342\002 Multiparty\\Prompt\\V1\\GPBMetadata\352\002\026Multiparty::Prompt::V1'
  _globals['_PROMPT']._serialized_start=90
  _globals['_PROMPT']._serialized_end=281
  _globals['_PROMPT_STATUS']._serialized_start=227
  _globals['_PROMPT_STATUS']._serialized_end=281
  _globals['_LISTPROMPTSREQUEST']._serialized_start=283
  _globals['_LISTPROMPTSREQUEST']._serialized_end=325
  _globals['_LISTPROMPTSRESPONSE']._serialized_start=327
  _globals['_LISTPROMPTSRESPONSE']._serialized_end=404
  _globals['_GETPROMPTREQUEST']._serialized_start=406
  _globals['_GETPROMPTREQUEST']._serialized_end=466
  _globals['_RESPONSE']._serialized_start=468
  _globals['_RESPONSE']._serialized_end=582
  _globals['_LISTRESPONSESREQUEST']._serialized_start=584
  _globals['_LISTRESPONSESREQUEST']._serialized_end=661
  _globals['_LISTRESPONSESRESPONSE']._serialized_start=663
  _globals['_LISTRESPONSESRESPONSE']._serialized_end=748
  _globals['_GETRESPONSEREQUEST']._serialized_start=750
  _globals['_GETRESPONSEREQUEST']._serialized_end=812
# @@protoc_insertion_point(module_scope)
